// <auto-generated />
namespace _2014214826_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ensambladora : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ensambladora));
        
        string IMigrationMetadata.Id
        {
            get { return "201705130429214_Ensambladora"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
